# Generated by Django 2.0.13 on 2019-08-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cruduser',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
