# Generated by Django 2.0.13 on 2019-08-26 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='name',
        ),
        migrations.AddField(
            model_name='cruduser',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cruduser',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='task',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cruduser',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='user2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='user',
            field=models.ManyToManyField(to='AppEnreda.User'),
        ),
    ]
