# Generated by Django 2.0.13 on 2019-08-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0002_auto_20190826_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruduser',
            name='adjunto',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='note',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='task',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cruduser',
            name='user2',
        ),
    ]
