# Generated by Django 2.0.13 on 2019-08-26 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0003_auto_20190826_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cruduser',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='task',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cruduser',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='user',
            field=models.ManyToManyField(to='AppEnreda.User'),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='user2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
