# Generated by Django 2.0.13 on 2019-08-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0003_cruduser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='user',
            new_name='creador',
        ),
    ]
