# Generated by Django 2.0.13 on 2019-08-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0004_auto_20190823_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='Prueba',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
