# Generated by Django 2.0.13 on 2019-08-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0004_auto_20190826_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Creador',
        ),
        migrations.RenameField(
            model_name='cruduser',
            old_name='user',
            new_name='creador',
        ),
        migrations.RenameField(
            model_name='cruduser',
            old_name='user2',
            new_name='creador2',
        ),
    ]
