# Generated by Django 2.0.13 on 2019-08-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0005_cruduser_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cruduser',
            old_name='Prueba',
            new_name='creador2',
        ),
    ]
