# Generated by Django 2.0.13 on 2019-08-24 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0006_auto_20190824_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='creador2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
