# Generated by Django 2.0.13 on 2019-08-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEnreda', '0008_cruduser_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruduser',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cruduser',
            name='task',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cruduser',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
